// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	transport "github.com/go-kratos/kratos/v2/transport"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	mux "github.com/gorilla/mux"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(http.Request)
var _ = new(context.Context)
var _ = new(middleware.Middleware)
var _ = new(transport.Transporter)
var _ = binding.BindVars
var _ = mux.NewRouter

const _ = http1.SupportPackageIsVersion1

type ShopInterfaceHandler interface {
	AddCartItem(context.Context, *AddCartItemReq) (*AddCartItemReply, error)

	CreateAddress(context.Context, *CreateAddressReq) (*CreateAddressReply, error)

	CreateCard(context.Context, *CreateCardReq) (*CreateCardReply, error)

	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderReply, error)

	DeleteCard(context.Context, *DeleteCardReq) (*DeleteCardReply, error)

	GetAddress(context.Context, *GetAddressReq) (*GetAddressReply, error)

	GetBeer(context.Context, *GetBeerReq) (*GetBeerReply, error)

	GetCard(context.Context, *GetCardReq) (*GetCardReply, error)

	ListAddress(context.Context, *ListAddressReq) (*ListAddressReply, error)

	ListBeer(context.Context, *ListBeerReq) (*ListBeerReply, error)

	ListCard(context.Context, *ListCardReq) (*ListCardReply, error)

	ListCartItem(context.Context, *ListCartItemReq) (*ListCartItemReply, error)

	ListOrder(context.Context, *ListOrderReq) (*ListOrderReply, error)

	Login(context.Context, *LoginReq) (*LoginReply, error)

	Logout(context.Context, *LogoutReq) (*LogoutReply, error)

	Register(context.Context, *RegisterReq) (*RegisterReply, error)
}

func NewShopInterfaceHandler(srv ShopInterfaceHandler, opts ...http1.HandleOption) http.Handler {
	h := http1.DefaultHandleOptions()
	for _, o := range opts {
		o(&h)
	}
	r := mux.NewRouter()

	r.HandleFunc("/v1/register", func(w http.ResponseWriter, r *http.Request) {
		var in RegisterReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/Register")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*RegisterReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/login", func(w http.ResponseWriter, r *http.Request) {
		var in LoginReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/Login")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*LoginReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/logout", func(w http.ResponseWriter, r *http.Request) {
		var in LogoutReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/Logout")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*LogoutReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/user/addresses", func(w http.ResponseWriter, r *http.Request) {
		var in ListAddressReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAddress(ctx, req.(*ListAddressReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/ListAddress")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*ListAddressReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/user/addresses", func(w http.ResponseWriter, r *http.Request) {
		var in CreateAddressReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAddress(ctx, req.(*CreateAddressReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/CreateAddress")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*CreateAddressReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/user/addresses/{id}", func(w http.ResponseWriter, r *http.Request) {
		var in GetAddressReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		if err := binding.BindVars(mux.Vars(r), &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAddress(ctx, req.(*GetAddressReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/GetAddress")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*GetAddressReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/user/cards", func(w http.ResponseWriter, r *http.Request) {
		var in ListCardReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCard(ctx, req.(*ListCardReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/ListCard")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*ListCardReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/user/cards", func(w http.ResponseWriter, r *http.Request) {
		var in CreateCardReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCard(ctx, req.(*CreateCardReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/CreateCard")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*CreateCardReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/user/cards/{id}", func(w http.ResponseWriter, r *http.Request) {
		var in GetCardReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		if err := binding.BindVars(mux.Vars(r), &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCard(ctx, req.(*GetCardReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/GetCard")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*GetCardReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/user/cards/{id}", func(w http.ResponseWriter, r *http.Request) {
		var in DeleteCardReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		if err := binding.BindVars(mux.Vars(r), &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCard(ctx, req.(*DeleteCardReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/DeleteCard")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*DeleteCardReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("DELETE")

	r.HandleFunc("/v1/catalog/beers", func(w http.ResponseWriter, r *http.Request) {
		var in ListBeerReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBeer(ctx, req.(*ListBeerReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/ListBeer")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*ListBeerReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/catalog/beers/{id}", func(w http.ResponseWriter, r *http.Request) {
		var in GetBeerReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		if err := binding.BindVars(mux.Vars(r), &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBeer(ctx, req.(*GetBeerReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/GetBeer")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*GetBeerReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/cart", func(w http.ResponseWriter, r *http.Request) {
		var in ListCartItemReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCartItem(ctx, req.(*ListCartItemReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/ListCartItem")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*ListCartItemReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/v1/cart", func(w http.ResponseWriter, r *http.Request) {
		var in AddCartItemReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddCartItem(ctx, req.(*AddCartItemReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/AddCartItem")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*AddCartItemReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/orders", func(w http.ResponseWriter, r *http.Request) {
		var in CreateOrderReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/CreateOrder")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*CreateOrderReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/v1/orders", func(w http.ResponseWriter, r *http.Request) {
		var in ListOrderReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrder(ctx, req.(*ListOrderReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		ctx := r.Context()
		transport.SetMethod(ctx, "/shop.interface.v1.ShopInterface/ListOrder")
		out, err := next(ctx, &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*ListOrderReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	return r
}

type ShopInterfaceHTTPClient interface {
	AddCartItem(ctx context.Context, req *AddCartItemReq, opts ...http1.CallOption) (rsp *AddCartItemReply, err error)

	CreateAddress(ctx context.Context, req *CreateAddressReq, opts ...http1.CallOption) (rsp *CreateAddressReply, err error)

	CreateCard(ctx context.Context, req *CreateCardReq, opts ...http1.CallOption) (rsp *CreateCardReply, err error)

	CreateOrder(ctx context.Context, req *CreateOrderReq, opts ...http1.CallOption) (rsp *CreateOrderReply, err error)

	DeleteCard(ctx context.Context, req *DeleteCardReq, opts ...http1.CallOption) (rsp *DeleteCardReply, err error)

	GetAddress(ctx context.Context, req *GetAddressReq, opts ...http1.CallOption) (rsp *GetAddressReply, err error)

	GetBeer(ctx context.Context, req *GetBeerReq, opts ...http1.CallOption) (rsp *GetBeerReply, err error)

	GetCard(ctx context.Context, req *GetCardReq, opts ...http1.CallOption) (rsp *GetCardReply, err error)

	ListAddress(ctx context.Context, req *ListAddressReq, opts ...http1.CallOption) (rsp *ListAddressReply, err error)

	ListBeer(ctx context.Context, req *ListBeerReq, opts ...http1.CallOption) (rsp *ListBeerReply, err error)

	ListCard(ctx context.Context, req *ListCardReq, opts ...http1.CallOption) (rsp *ListCardReply, err error)

	ListCartItem(ctx context.Context, req *ListCartItemReq, opts ...http1.CallOption) (rsp *ListCartItemReply, err error)

	ListOrder(ctx context.Context, req *ListOrderReq, opts ...http1.CallOption) (rsp *ListOrderReply, err error)

	Login(ctx context.Context, req *LoginReq, opts ...http1.CallOption) (rsp *LoginReply, err error)

	Logout(ctx context.Context, req *LogoutReq, opts ...http1.CallOption) (rsp *LogoutReply, err error)

	Register(ctx context.Context, req *RegisterReq, opts ...http1.CallOption) (rsp *RegisterReply, err error)
}

type ShopInterfaceHTTPClientImpl struct {
	cc *http1.Client
}

func NewShopInterfaceHTTPClient(client *http1.Client) ShopInterfaceHTTPClient {
	return &ShopInterfaceHTTPClientImpl{client}
}

func (c *ShopInterfaceHTTPClientImpl) AddCartItem(ctx context.Context, in *AddCartItemReq, opts ...http1.CallOption) (*AddCartItemReply, error) {
	var out AddCartItemReply
	path := binding.EncodePath("POST", "/v1/cart", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/AddCartItem"))

	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...http1.CallOption) (*CreateAddressReply, error) {
	var out CreateAddressReply
	path := binding.EncodePath("POST", "/v1/user/addresses", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/CreateAddress"))

	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) CreateCard(ctx context.Context, in *CreateCardReq, opts ...http1.CallOption) (*CreateCardReply, error) {
	var out CreateCardReply
	path := binding.EncodePath("POST", "/v1/user/cards", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/CreateCard"))

	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...http1.CallOption) (*CreateOrderReply, error) {
	var out CreateOrderReply
	path := binding.EncodePath("POST", "/v1/orders", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/CreateOrder"))

	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) DeleteCard(ctx context.Context, in *DeleteCardReq, opts ...http1.CallOption) (*DeleteCardReply, error) {
	var out DeleteCardReply
	path := binding.EncodePath("DELETE", "/v1/user/cards/{id}", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/DeleteCard"))

	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) GetAddress(ctx context.Context, in *GetAddressReq, opts ...http1.CallOption) (*GetAddressReply, error) {
	var out GetAddressReply
	path := binding.EncodePath("GET", "/v1/user/addresses/{id}", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/GetAddress"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) GetBeer(ctx context.Context, in *GetBeerReq, opts ...http1.CallOption) (*GetBeerReply, error) {
	var out GetBeerReply
	path := binding.EncodePath("GET", "/v1/catalog/beers/{id}", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/GetBeer"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) GetCard(ctx context.Context, in *GetCardReq, opts ...http1.CallOption) (*GetCardReply, error) {
	var out GetCardReply
	path := binding.EncodePath("GET", "/v1/user/cards/{id}", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/GetCard"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) ListAddress(ctx context.Context, in *ListAddressReq, opts ...http1.CallOption) (*ListAddressReply, error) {
	var out ListAddressReply
	path := binding.EncodePath("GET", "/v1/user/addresses", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/ListAddress"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) ListBeer(ctx context.Context, in *ListBeerReq, opts ...http1.CallOption) (*ListBeerReply, error) {
	var out ListBeerReply
	path := binding.EncodePath("GET", "/v1/catalog/beers", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/ListBeer"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) ListCard(ctx context.Context, in *ListCardReq, opts ...http1.CallOption) (*ListCardReply, error) {
	var out ListCardReply
	path := binding.EncodePath("GET", "/v1/user/cards", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/ListCard"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) ListCartItem(ctx context.Context, in *ListCartItemReq, opts ...http1.CallOption) (*ListCartItemReply, error) {
	var out ListCartItemReply
	path := binding.EncodePath("GET", "/v1/cart", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/ListCartItem"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) ListOrder(ctx context.Context, in *ListOrderReq, opts ...http1.CallOption) (*ListOrderReply, error) {
	var out ListOrderReply
	path := binding.EncodePath("GET", "/v1/orders", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/ListOrder"))

	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) Login(ctx context.Context, in *LoginReq, opts ...http1.CallOption) (*LoginReply, error) {
	var out LoginReply
	path := binding.EncodePath("POST", "/v1/login", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/Login"))

	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) Logout(ctx context.Context, in *LogoutReq, opts ...http1.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	path := binding.EncodePath("POST", "/v1/logout", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/Logout"))

	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)

	return &out, err
}

func (c *ShopInterfaceHTTPClientImpl) Register(ctx context.Context, in *RegisterReq, opts ...http1.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	path := binding.EncodePath("POST", "/v1/register", in)
	opts = append(opts, http1.Method("/shop.interface.v1.ShopInterface/Register"))

	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)

	return &out, err
}
