// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/beer-shop/project/app/user-service/internal/biz"
	"github.com/go-kratos/beer-shop/project/app/user-service/internal/conf"
	"github.com/go-kratos/beer-shop/project/app/user-service/internal/data"
	"github.com/go-kratos/beer-shop/project/app/user-service/internal/server"
	"github.com/go-kratos/beer-shop/project/app/user-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, error) {
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	cardRepo := data.NewCardRepo(dataData, logger)
	cardUseCase := biz.NewCardUseCase(cardRepo, logger)
	addressRepo := data.NewAddressRepo(dataData, logger)
	addressUseCase := biz.NewAddressUseCase(addressRepo, logger)
	userService := service.NewUserService(userUseCase, cardUseCase, addressUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, userService)
	grpcServer := server.NewGRPCServer(confServer, userService)
	registrar := server.NewRegistrar()
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, nil
}
