// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	mux "github.com/gorilla/mux"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(http.Request)
var _ = new(context.Context)
var _ = binding.MapProto
var _ = mux.NewRouter

const _ = http1.SupportPackageIsVersion1

type OrderHandler interface {
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderReply, error)

	GetOrder(context.Context, *GetOrderReq) (*GetOrderReply, error)

	ListOrder(context.Context, *ListOrderReq) (*ListOrderReply, error)

	UpdateOrder(context.Context, *UpdateOrderReq) (*UpdateOrderReply, error)
}

func NewOrderHandler(srv OrderHandler, opts ...http1.HandleOption) http.Handler {
	h := http1.DefaultHandleOptions()
	for _, o := range opts {
		o(&h)
	}
	r := mux.NewRouter()

	r.HandleFunc("/cart.service.v1.Order/ListOrder", func(w http.ResponseWriter, r *http.Request) {
		var in ListOrderReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrder(ctx, req.(*ListOrderReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*ListOrderReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/cart.service.v1.Order/CreateOrder", func(w http.ResponseWriter, r *http.Request) {
		var in CreateOrderReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*CreateOrderReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/cart.service.v1.Order/GetOrder", func(w http.ResponseWriter, r *http.Request) {
		var in GetOrderReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*GetOrderReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/cart.service.v1.Order/UpdateOrder", func(w http.ResponseWriter, r *http.Request) {
		var in UpdateOrderReq
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOrder(ctx, req.(*UpdateOrderReq))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*UpdateOrderReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	return r
}

type OrderHttpClient interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq, opts ...http1.CallOption) (rsp *CreateOrderReply, err error)

	GetOrder(ctx context.Context, req *GetOrderReq, opts ...http1.CallOption) (rsp *GetOrderReply, err error)

	ListOrder(ctx context.Context, req *ListOrderReq, opts ...http1.CallOption) (rsp *ListOrderReply, err error)

	UpdateOrder(ctx context.Context, req *UpdateOrderReq, opts ...http1.CallOption) (rsp *UpdateOrderReply, err error)
}

type OrderHttpClientImpl struct {
	cc *http1.Client
}

func NewOrderHttpClient(client *http1.Client) OrderHttpClient {
	return &OrderHttpClientImpl{client}
}

func (c *OrderHttpClientImpl) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...http1.CallOption) (out *CreateOrderReply, err error) {
	path := binding.EncodePath("POST", "/cart.service.v1.Order/CreateOrder", in)
	out = &CreateOrderReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/cart.service.v1.Order/CreateOrder"))

	if err != nil {
		return
	}
	return
}

func (c *OrderHttpClientImpl) GetOrder(ctx context.Context, in *GetOrderReq, opts ...http1.CallOption) (out *GetOrderReply, err error) {
	path := binding.EncodePath("POST", "/cart.service.v1.Order/GetOrder", in)
	out = &GetOrderReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/cart.service.v1.Order/GetOrder"))

	if err != nil {
		return
	}
	return
}

func (c *OrderHttpClientImpl) ListOrder(ctx context.Context, in *ListOrderReq, opts ...http1.CallOption) (out *ListOrderReply, err error) {
	path := binding.EncodePath("POST", "/cart.service.v1.Order/ListOrder", in)
	out = &ListOrderReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/cart.service.v1.Order/ListOrder"))

	if err != nil {
		return
	}
	return
}

func (c *OrderHttpClientImpl) UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...http1.CallOption) (out *UpdateOrderReply, err error) {
	path := binding.EncodePath("POST", "/cart.service.v1.Order/UpdateOrder", in)
	out = &UpdateOrderReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/cart.service.v1.Order/UpdateOrder"))

	if err != nil {
		return
	}
	return
}
