// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.0-rc3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ShopAdminHTTPServer interface {
	CreateBeer(context.Context, *CreateBeerReq) (*CreateBeerReply, error)
	DeleteBeer(context.Context, *DeleteBeerReq) (*DeleteBeerReply, error)
	GetCustomer(context.Context, *GetCustomerReq) (*GetCustomerReply, error)
	GetOrder(context.Context, *GetOrderReq) (*GetOrderReply, error)
	ListBeer(context.Context, *ListBeerReq) (*ListBeerReply, error)
	ListCustomer(context.Context, *ListCustomerReq) (*ListCustomerReply, error)
	ListOrder(context.Context, *ListOrderReq) (*ListOrderReply, error)
	Login(context.Context, *LoginReq) (*LoginReply, error)
	Logout(context.Context, *LogoutReq) (*LogoutReply, error)
	UpdateBeer(context.Context, *UpdateBeerReq) (*UpdateBeerReply, error)
}

func RegisterShopAdminHTTPServer(s *http.Server, srv ShopAdminHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/login", _ShopAdmin_Login0_HTTP_Handler(srv))
	r.POST("/admin/v1/logout", _ShopAdmin_Logout0_HTTP_Handler(srv))
	r.GET("/admin/v1/catalog/beers", _ShopAdmin_ListBeer0_HTTP_Handler(srv))
	r.POST("/admin/v1/catalog/beers", _ShopAdmin_CreateBeer0_HTTP_Handler(srv))
	r.PUT("/admin/v1/catalog/beers/{id}", _ShopAdmin_UpdateBeer0_HTTP_Handler(srv))
	r.DELETE("/admin/v1/catalog/beers/{id}", _ShopAdmin_DeleteBeer0_HTTP_Handler(srv))
	r.GET("/admin/v1/orders", _ShopAdmin_ListOrder0_HTTP_Handler(srv))
	r.GET("/admin/v1/orders", _ShopAdmin_GetOrder0_HTTP_Handler(srv))
	r.GET("/admin/v1/customers", _ShopAdmin_ListCustomer0_HTTP_Handler(srv))
	r.POST("/admin/v1/customers/{id}", _ShopAdmin_GetCustomer0_HTTP_Handler(srv))
}

func _ShopAdmin_Login0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/Login")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_Logout0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/Logout")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_ListBeer0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBeerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/ListBeer")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBeer(ctx, req.(*ListBeerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBeerReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_CreateBeer0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBeerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/CreateBeer")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBeer(ctx, req.(*CreateBeerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBeerReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_UpdateBeer0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBeerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/UpdateBeer")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBeer(ctx, req.(*UpdateBeerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateBeerReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_DeleteBeer0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBeerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/DeleteBeer")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBeer(ctx, req.(*DeleteBeerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteBeerReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_ListOrder0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/ListOrder")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrder(ctx, req.(*ListOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrderReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_GetOrder0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/GetOrder")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_ListCustomer0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCustomerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/ListCustomer")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCustomer(ctx, req.(*ListCustomerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCustomerReply)
		return ctx.Result(200, reply)
	}
}

func _ShopAdmin_GetCustomer0_HTTP_Handler(srv ShopAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCustomerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.admin.v1.ShopAdmin/GetCustomer")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCustomer(ctx, req.(*GetCustomerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCustomerReply)
		return ctx.Result(200, reply)
	}
}

type ShopAdminHTTPClient interface {
	CreateBeer(ctx context.Context, req *CreateBeerReq, opts ...http.CallOption) (rsp *CreateBeerReply, err error)
	DeleteBeer(ctx context.Context, req *DeleteBeerReq, opts ...http.CallOption) (rsp *DeleteBeerReply, err error)
	GetCustomer(ctx context.Context, req *GetCustomerReq, opts ...http.CallOption) (rsp *GetCustomerReply, err error)
	GetOrder(ctx context.Context, req *GetOrderReq, opts ...http.CallOption) (rsp *GetOrderReply, err error)
	ListBeer(ctx context.Context, req *ListBeerReq, opts ...http.CallOption) (rsp *ListBeerReply, err error)
	ListCustomer(ctx context.Context, req *ListCustomerReq, opts ...http.CallOption) (rsp *ListCustomerReply, err error)
	ListOrder(ctx context.Context, req *ListOrderReq, opts ...http.CallOption) (rsp *ListOrderReply, err error)
	Login(ctx context.Context, req *LoginReq, opts ...http.CallOption) (rsp *LoginReply, err error)
	Logout(ctx context.Context, req *LogoutReq, opts ...http.CallOption) (rsp *LogoutReply, err error)
	UpdateBeer(ctx context.Context, req *UpdateBeerReq, opts ...http.CallOption) (rsp *UpdateBeerReply, err error)
}

type ShopAdminHTTPClientImpl struct {
	cc *http.Client
}

func NewShopAdminHTTPClient(client *http.Client) ShopAdminHTTPClient {
	return &ShopAdminHTTPClientImpl{client}
}

func (c *ShopAdminHTTPClientImpl) CreateBeer(ctx context.Context, in *CreateBeerReq, opts ...http.CallOption) (*CreateBeerReply, error) {
	var out CreateBeerReply
	path := binding.EncodeURL("/admin/v1/catalog/beers", in, false)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/CreateBeer"))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) DeleteBeer(ctx context.Context, in *DeleteBeerReq, opts ...http.CallOption) (*DeleteBeerReply, error) {
	var out DeleteBeerReply
	path := binding.EncodeURL("/admin/v1/catalog/beers/{id}", in, false)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/DeleteBeer"))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) GetCustomer(ctx context.Context, in *GetCustomerReq, opts ...http.CallOption) (*GetCustomerReply, error) {
	var out GetCustomerReply
	path := binding.EncodeURL("/admin/v1/customers/{id}", in, false)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/GetCustomer"))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) GetOrder(ctx context.Context, in *GetOrderReq, opts ...http.CallOption) (*GetOrderReply, error) {
	var out GetOrderReply
	path := binding.EncodeURL("/admin/v1/orders", in, true)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/GetOrder"))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) ListBeer(ctx context.Context, in *ListBeerReq, opts ...http.CallOption) (*ListBeerReply, error) {
	var out ListBeerReply
	path := binding.EncodeURL("/admin/v1/catalog/beers", in, true)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/ListBeer"))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) ListCustomer(ctx context.Context, in *ListCustomerReq, opts ...http.CallOption) (*ListCustomerReply, error) {
	var out ListCustomerReply
	path := binding.EncodeURL("/admin/v1/customers", in, true)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/ListCustomer"))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) ListOrder(ctx context.Context, in *ListOrderReq, opts ...http.CallOption) (*ListOrderReply, error) {
	var out ListOrderReply
	path := binding.EncodeURL("/admin/v1/orders", in, true)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/ListOrder"))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) Login(ctx context.Context, in *LoginReq, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	path := binding.EncodeURL("/admin/v1/login", in, false)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/Login"))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) Logout(ctx context.Context, in *LogoutReq, opts ...http.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	path := binding.EncodeURL("/admin/v1/logout", in, false)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/Logout"))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopAdminHTTPClientImpl) UpdateBeer(ctx context.Context, in *UpdateBeerReq, opts ...http.CallOption) (*UpdateBeerReply, error) {
	var out UpdateBeerReply
	path := binding.EncodeURL("/admin/v1/catalog/beers/{id}", in, false)
	opts = append(opts, http.Operation("/shop.admin.v1.ShopAdmin/UpdateBeer"))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
