// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

const (
	Errors_UNKNOWN_ERROR  = "Cart_UNKNOWN_ERROR"
	Errors_ITEM_NOT_FOUND = "Cart_ITEM_NOT_FOUND"
)

func IsUNKNOWN_ERROR(err error) bool {
	return errors.Reason(err) == Errors_UNKNOWN_ERROR
}

func IsITEM_NOT_FOUND(err error) bool {
	return errors.Reason(err) == Errors_ITEM_NOT_FOUND
}
