trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  mongodb:
    uri: "mongodb://localhost:27017/"
    database: "cart-db"
